"""Added post formatting to bots

Revision ID: 20b723222043
Revises: 9868b546f0ee
Create Date: 2024-06-27 14:48:22.947908

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '20b723222043'
down_revision: Union[str, None] = '9868b546f0ee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bot', sa.Column('post_formatting', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bot', 'post_formatting')
    # ### end Alembic commands ###
