"""Deleted answers table

Revision ID: 25d2710b23bd
Revises: 8fc76dd8fe6c
Create Date: 2024-06-12 13:09:47.342463

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '25d2710b23bd'
down_revision: Union[str, None] = '8fc76dd8fe6c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('answer')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('answer',
    sa.Column('message_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['message_id'], ['suggested_message.id'], name='answer_message_id_fkey'),
    sa.PrimaryKeyConstraint('message_id', name='answer_pkey')
    )
    # ### end Alembic commands ###
