"""Channel ids are not more unique

Revision ID: 316e6976a9d7
Revises: 6a3eb65e7a6a
Create Date: 2024-08-22 19:13:28.948752

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '316e6976a9d7'
down_revision: Union[str, None] = '6a3eb65e7a6a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
