"""Added group_id and chat_id to messages table

Revision ID: 39ac3d720233
Revises: d6af391c775e
Create Date: 2024-06-23 19:21:37.319131

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '39ac3d720233'
down_revision: Union[str, None] = 'd6af391c775e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('suggested_message', sa.Column('chat_id', sa.BigInteger(), nullable=False))
    op.add_column('suggested_message', sa.Column('group_id', sa.String(length=255), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('suggested_message', 'group_id')
    op.drop_column('suggested_message', 'chat_id')
    # ### end Alembic commands ###
