"""Add label field to Admin

Revision ID: 3d8f1d0f2dbc
Revises: 55784e8aac7b
Create Date: 2024-08-10 19:54:23.707062

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3d8f1d0f2dbc'
down_revision: Union[str, None] = '55784e8aac7b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('admin', sa.Column('label', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('admin', 'label')
    # ### end Alembic commands ###
