"""added tables for ads and mailing messages

Revision ID: 3e7ec59f0faf
Revises: 59a6419e3990
Create Date: 2024-07-03 13:22:45.131336

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3e7ec59f0faf'
down_revision: Union[str, None] = '59a6419e3990'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ad_message',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('html_text', sa.Text(), nullable=False),
    sa.Column('message_data', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mailing_message',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('html_text', sa.Text(), nullable=False),
    sa.Column('inline_text', sa.String(length=255), nullable=False),
    sa.Column('inline_url', sa.String(length=255), nullable=False),
    sa.Column('message_data', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('mailing_message')
    op.drop_table('ad_message')
    # ### end Alembic commands ###
