"""Added InviteCodes table

Revision ID: 5470abc3be2d
Revises: a768eac7bf17
Create Date: 2024-06-25 16:38:13.488294

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5470abc3be2d'
down_revision: Union[str, None] = 'a768eac7bf17'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('invite_codes',
    sa.Column('code', sa.String(length=255), nullable=False),
    sa.Column('bot_id', sa.BigInteger(), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='True', nullable=False),
    sa.PrimaryKeyConstraint('code')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('invite_codes')
    # ### end Alembic commands ###
