"""Add label field to Admin

Revision ID: 55784e8aac7b
Revises: b4c59736ad1d
Create Date: 2024-08-10 19:48:24.924527

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '55784e8aac7b'
down_revision: Union[str, None] = 'b4c59736ad1d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('admin', sa.Column('label', sa.String(length=255), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('admin', 'label')
    # ### end Alembic commands ###
