"""Added some is_active and is_premium fields

Revision ID: 7288bbb863cc
Revises: 9d5f19a83fb6
Create Date: 2024-06-28 19:28:50.678738

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7288bbb863cc'
down_revision: Union[str, None] = '9d5f19a83fb6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('admin', sa.Column('is_active', sa.Boolean(), server_default='True', nullable=False))
    op.add_column('bot', sa.Column('is_premium', sa.Boolean(), server_default='False', nullable=False))
    op.add_column('sender', sa.Column('is_active', sa.Boolean(), server_default='True', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sender', 'is_active')
    op.drop_column('bot', 'is_premium')
    op.drop_column('admin', 'is_active')
    # ### end Alembic commands ###
