"""Added AdMessageViews

Revision ID: 72e570dbaf04
Revises: 7288bbb863cc
Create Date: 2024-07-02 16:33:39.610425

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '72e570dbaf04'
down_revision: Union[str, None] = '7288bbb863cc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ad_message_views',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('view_date', sa.Date(), nullable=False),
    sa.Column('view_count', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('subscription', sa.Column('plan', sa.String(length=255), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('subscription', 'plan')
    op.drop_table('ad_message_views')
    # ### end Alembic commands ###
