"""mapped columns

Revision ID: 8dc558ffec5e
Revises: 3e7ec59f0faf
Create Date: 2024-07-03 13:27:09.886306

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8dc558ffec5e'
down_revision: Union[str, None] = '3e7ec59f0faf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('ad_message_views', 'view_count',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('ad_message_views', 'view_count',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
