"""Added media_group_id to messages

Revision ID: 9868b546f0ee
Revises: 3c6fd367e6c1
Create Date: 2024-06-26 14:29:17.227358

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9868b546f0ee'
down_revision: Union[str, None] = '3c6fd367e6c1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('suggested_message', sa.Column('media_group_id', sa.String(length=255), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('suggested_message', 'media_group_id')
    # ### end Alembic commands ###
