"""Added html_text to messages

Revision ID: 9d5f19a83fb6
Revises: 20b723222043
Create Date: 2024-06-27 17:01:23.308085

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9d5f19a83fb6'
down_revision: Union[str, None] = '20b723222043'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('suggested_message', sa.Column('html_text', sa.Text(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('suggested_message', 'html_text')
    # ### end Alembic commands ###
