"""added photo link to ads

Revision ID: b4c59736ad1d
Revises: 8dc558ffec5e
Create Date: 2024-07-04 12:04:45.580664

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b4c59736ad1d'
down_revision: Union[str, None] = '8dc558ffec5e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ad_message', sa.Column('photo_link', sa.String(length=255), nullable=True))
    op.alter_column('ad_message', 'message_data',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('ad_message', 'message_data',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=False)
    op.drop_column('ad_message', 'photo_link')
    # ### end Alembic commands ###
