"""Changed primary_key for suggested messages

Revision ID: c131f0db79ad
Revises: 3d8f1d0f2dbc
Create Date: 2024-08-14 12:14:28.807368

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c131f0db79ad'
down_revision: Union[str, None] = '3d8f1d0f2dbc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('suggested_message', sa.Column('primary_key', sa.BigInteger(), autoincrement=True, nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('suggested_message', 'primary_key')
    # ### end Alembic commands ###
