"""added more formatting options

Revision ID: d55c75f5ba4a
Revises: 0fa7871c5bcd
Create Date: 2024-10-04 23:34:29.547320

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd55c75f5ba4a'
down_revision: Union[str, None] = '0fa7871c5bcd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bot', sa.Column('start_message', sa.String(length=255), nullable=True))
    op.add_column('bot', sa.Column('answer_message', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bot', 'answer_message')
    op.drop_column('bot', 'start_message')
    # ### end Alembic commands ###
