"""Add banlist to bot

Revision ID: da9c8e75bc60
Revises: f1db2ee49f9a
Create Date: 2024-06-20 14:54:33.409090

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'da9c8e75bc60'
down_revision: Union[str, None] = 'f1db2ee49f9a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bot', sa.Column('banlist', sa.ARRAY(sa.BigInteger()), nullable=True))
    op.drop_constraint('bot_admin_id_fkey', 'bot', type_='foreignkey')
    op.drop_column('bot', 'admin_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bot', sa.Column('admin_id', sa.BIGINT(), autoincrement=False, nullable=False))
    op.create_foreign_key('bot_admin_id_fkey', 'bot', 'admin', ['admin_id'], ['id'])
    op.drop_column('bot', 'banlist')
    # ### end Alembic commands ###
